import path from 'node:path'
import { DATA_DIR } from '@/lib/server/data-dir'
export {
  DEFAULT_SANDBOX_IMAGE,
  DEFAULT_SANDBOX_CONTAINER_PREFIX,
  DEFAULT_SANDBOX_WORKDIR,
  DEFAULT_SANDBOX_BROWSER_IMAGE,
  DEFAULT_SANDBOX_BROWSER_PREFIX,
  DEFAULT_SANDBOX_BROWSER_NETWORK,
  DEFAULT_SANDBOX_BROWSER_CDP_PORT,
  DEFAULT_SANDBOX_BROWSER_VNC_PORT,
  DEFAULT_SANDBOX_BROWSER_NOVNC_PORT,
  DEFAULT_SANDBOX_BROWSER_AUTOSTART_TIMEOUT_MS,
  DEFAULT_SANDBOX_BROWSER_HEADLESS,
  DEFAULT_SANDBOX_BROWSER_MOUNT_UPLOADS,
  DEFAULT_SANDBOX_BROWSER_ENABLE_NOVNC,
  DEFAULT_SANDBOX_PRUNE_IDLE_HOURS,
  DEFAULT_SANDBOX_PRUNE_MAX_AGE_DAYS,
} from '@/lib/sandbox-defaults'

export const SANDBOX_UPLOADS_MOUNT = '/uploads'
export const SANDBOX_STATE_DIR = path.join(DATA_DIR, 'sandbox')
export const SANDBOX_REGISTRY_PATH = path.join(SANDBOX_STATE_DIR, 'containers.json')
export const SANDBOX_BROWSER_REGISTRY_PATH = path.join(SANDBOX_STATE_DIR, 'browsers.json')
