import crypto from 'crypto'
import type { Mission, MissionEvent, MissionReport } from '@/types'
import { getRecentMessages } from '@/lib/server/messages/message-repository'
import { listMissionEvents } from './mission-repository'

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`
  const sec = Math.round(ms / 1000)
  if (sec < 60) return `${sec}s`
  const min = Math.round(sec / 60)
  if (min < 60) return `${min}m`
  const hr = Math.round(min / 60 * 10) / 10
  return `${hr}h`
}

function formatUsd(n: number): string {
  return `$${n.toFixed(n < 0.01 ? 4 : 2)}`
}

function formatWhen(at: number): string {
  try {
    return new Date(at).toISOString().replace('T', ' ').slice(0, 19) + ' UTC'
  } catch {
    return String(at)
  }
}

export interface MissionReportOptions {
  isFinal?: boolean
  windowSource?: 'schedule' | 'final' | 'on_demand'
}

export interface BuiltMissionReport {
  report: MissionReport
  deliveryMessage: string
  deliveryTitle: string
}

function extractHighlights(events: MissionEvent[]): MissionReport['highlights'] {
  const milestones = events.filter((e) => e.kind.startsWith('milestone:'))
  return milestones.slice(-5).map((ev) => ({
    kind: ev.kind,
    summary: typeof ev.payload.summary === 'string' ? ev.payload.summary : ev.kind,
    evidenceRunId: ev.runId ?? null,
  }))
}

function collectRecentTranscriptLines(missionRootSessionId: string, window: { from: number; to: number }): string[] {
  try {
    const messages = getRecentMessages(missionRootSessionId, 40)
    return messages
      .filter((m) => {
        const ts = typeof m.time === 'number' ? m.time : 0
        return ts >= window.from && ts <= window.to
      })
      .slice(-20)
      .map((m) => {
        const role = m.role || 'system'
        const text = (typeof m.text === 'string' ? m.text : '').split('\n')[0].slice(0, 280)
        return `- **${role}**: ${text}`
      })
  } catch {
    return []
  }
}

export function renderMissionReportMarkdown(
  mission: Mission,
  events: MissionEvent[],
  transcriptLines: string[],
  window: { from: number; to: number },
  opts: MissionReportOptions,
): { title: string; body: string } {
  const title = opts.isFinal
    ? `${mission.title}: final report`
    : `${mission.title}: progress update`

  const parts: string[] = []
  parts.push(`# ${title}`)
  parts.push('')
  parts.push(`**Goal**: ${mission.goal}`)
  parts.push('')
  parts.push(`**Status**: \`${mission.status}\``)
  parts.push('')
  parts.push(`**Window**: ${formatWhen(window.from)} to ${formatWhen(window.to)}`)
  parts.push('')

  parts.push('## Usage')
  parts.push(`- Turns run: ${mission.usage.turnsRun}${mission.budget.maxTurns != null ? ` / ${mission.budget.maxTurns}` : ''}`)
  parts.push(`- Tokens used: ${mission.usage.tokensUsed}${mission.budget.maxTokens != null ? ` / ${mission.budget.maxTokens}` : ''}`)
  parts.push(`- Spend: ${formatUsd(mission.usage.usdSpent)}${mission.budget.maxUsd != null ? ` / ${formatUsd(mission.budget.maxUsd)}` : ''}`)
  parts.push(`- Wallclock: ${formatDuration(mission.usage.wallclockMsElapsed)}${mission.budget.maxWallclockSec != null ? ` / ${formatDuration(mission.budget.maxWallclockSec * 1000)}` : ''}`)
  parts.push('')

  if (mission.successCriteria.length > 0) {
    parts.push('## Success criteria')
    for (const c of mission.successCriteria) parts.push(`- ${c}`)
    parts.push('')
  }

  const milestones = events.filter((e) => e.kind.startsWith('milestone:'))
  if (milestones.length > 0) {
    parts.push(`## Milestones (${milestones.length})`)
    for (const ev of milestones.slice(-20)) {
      const kind = ev.kind.replace('milestone:', '')
      const summary = typeof ev.payload.summary === 'string' ? ev.payload.summary : kind
      parts.push(`- **${kind}** at ${formatWhen(ev.at)}: ${summary}`)
    }
    parts.push('')
  }

  if (transcriptLines.length > 0) {
    parts.push('## Recent activity')
    for (const line of transcriptLines) parts.push(line)
    parts.push('')
  }

  if (opts.isFinal && mission.endReason) {
    parts.push('## End reason')
    parts.push(mission.endReason)
    parts.push('')
  }

  parts.push('---')
  parts.push('_Generated by SwarmClaw Missions._')

  return { title, body: parts.join('\n') }
}

export function buildMissionReport(
  mission: Mission,
  window: { from: number; to: number },
  opts: MissionReportOptions = {},
): BuiltMissionReport {
  const events = listMissionEvents(mission.id, { sinceAt: window.from, untilAt: window.to })
  const transcriptLines = collectRecentTranscriptLines(mission.rootSessionId, window)
  const { title, body } = renderMissionReportMarkdown(mission, events, transcriptLines, window, opts)

  const report: MissionReport = {
    id: `mrep_${crypto.randomBytes(8).toString('hex')}`,
    missionId: mission.id,
    generatedAt: Date.now(),
    format: 'markdown',
    fromAt: window.from,
    toAt: window.to,
    title,
    body,
    audioUrl: null,
    deliveredTo: [],
    highlights: extractHighlights(events),
  }

  const deliveryMessage = opts.isFinal
    ? `Mission "${mission.title}" has ended. Open SwarmClaw to review the final report.`
    : `Mission "${mission.title}" is still running. ${mission.usage.turnsRun} turns done.`

  return { report, deliveryMessage, deliveryTitle: title }
}
