import type { AppView } from '@/types'

export const VIEW_LABELS: Record<AppView, string> = {
  home: 'Home',
  agents: 'Agents',
  inbox: 'Inbox',
  chatrooms: 'Chatrooms',
  schedules: 'Schedules',
  memory: 'Memory',
  tasks: 'Tasks',
  secrets: 'Secrets',
  providers: 'Providers',
  skills: 'Skills',
  connectors: 'Connectors',
  webhooks: 'Webhooks',
  mcp_servers: 'MCP Servers',
  knowledge: 'Knowledge',
  logs: 'Logs',
  plugins: 'Plugins',
  usage: 'Usage',
  wallets: 'Wallets',
  runs: 'Runs',
  settings: 'Settings',
  projects: 'Projects',
  activity: 'Activity',
}

export const CREATE_LABELS: Partial<Record<AppView, string>> = {
  agents: 'Agent',
  schedules: 'Schedule',
  tasks: 'Task',
  secrets: 'Secret',
  providers: 'Provider',
  skills: 'Skill',
  connectors: 'Connector',
  webhooks: 'Webhook',
  mcp_servers: 'MCP Server',
  knowledge: 'Knowledge Entry',
  plugins: 'Plugin',
  projects: 'Project',
}

export const VIEW_DESCRIPTIONS: Record<AppView, string> = {
  home: 'SwarmClaw overview',
  agents: 'Chat with & configure your AI agents',
  inbox: 'Review external connector conversations by platform and bridge',
  chatrooms: 'Multi-agent collaborative chatrooms',
  schedules: 'Automated task schedules',
  memory: 'Long-term agent memory store',
  tasks: 'Task board for agent work and queued runs',
  secrets: 'API keys, tokens, and encrypted credentials',
  providers: 'LLM providers & custom endpoints',
  skills: 'Reusable instruction sets for agents',
  connectors: 'Chat platform bridges (Discord, Slack, etc.)',
  webhooks: 'Inbound HTTP triggers for event-driven workflows',
  mcp_servers: 'Connect agents to external MCP tool servers',
  knowledge: 'Shared knowledge base accessible by all agents',
  logs: 'Application logs & error tracking',
  plugins: 'Extend agent capabilities with custom plugins',
  usage: 'Usage metrics, cost tracking & agent performance',
  wallets: 'Agent crypto wallets — hold funds, send SOL, manage spending',
  runs: 'Live run monitoring & history',
  settings: 'Manage defaults, providers, secrets, and automation settings',
  projects: 'Group agents, tasks & schedules into projects',
  activity: 'Audit trail of all entity mutations',
}

export const VIEW_EMPTY_STATES: Record<Exclude<AppView, 'agents' | 'home'>, { icon: string; title: string; description: string; features: string[] }> = {
  chatrooms: {
    icon: 'message-square',
    title: 'Chatrooms',
    description: 'Multi-agent chatrooms for collaborative conversations. Add agents and use @mentions to trigger responses.',
    features: ['Create chatrooms with multiple AI agents', 'Use @AgentName to trigger specific agents', '@all mentions trigger all agents sequentially', 'Agents can chain by mentioning each other'],
  },
  schedules: {
    icon: 'clock',
    title: 'Schedules',
    description: 'Automate recurring work with cron, interval, or one-time schedules that launch agent tasks.',
    features: ['Set up cron expressions for precise timing', 'Run agents automatically on intervals', 'Schedule one-time future tasks', 'View execution history and results'],
  },
  memory: {
    icon: 'database',
    title: 'Memory',
    description: 'Long-term memory store for AI agents so they can retain useful context across conversations.',
    features: ['Agents store findings and learnings automatically', 'Full-text search across all stored memories', 'Organized by categories and agents', 'Persists across conversations for continuity'],
  },
  tasks: {
    icon: 'clipboard',
    title: 'Task Board',
    description: 'A kanban board for managing agent work. Create tasks, assign them to agents, and track progress.',
    features: ['Kanban columns: Backlog, Queued, Running, Completed, Failed', 'Assign tasks to specific agents', 'Track retries, results, and logs', 'Review status without leaving the board'],
  },
  secrets: {
    icon: 'lock',
    title: 'Secrets',
    description: 'Manage API keys and credentials that agents and integrations can access securely.',
    features: ['Store keys for external services (Gmail, APIs, etc.)', 'Scope secrets globally or to specific agents', 'Encrypted at rest with AES-256-GCM', 'Agents retrieve secrets through configured tools'],
  },
  providers: {
    icon: 'zap',
    title: 'Providers',
    description: 'Manage LLM providers including built-in and custom OpenAI-compatible endpoints.',
    features: ['Built-in support for Claude, OpenAI, Anthropic, and Ollama', 'Add custom OpenAI-compatible providers (OpenRouter, Together, Groq)', 'Configure base URLs, models, and API keys per provider', 'Custom providers work seamlessly with all features'],
  },
  skills: {
    icon: 'book',
    title: 'Skills',
    description: 'Manage reusable instruction sets, runtime skill selection, and reviewed skill drafts generated from real conversations.',
    features: ['Upload markdown files with specialized instructions', 'Approve reviewed skill drafts from conversations', 'Assign skills to specific agents', 'Use runtime skill recommendations during execution'],
  },
  connectors: {
    icon: 'link',
    title: 'Connectors',
    description: 'Bridge chat platforms to your AI agents. Receive messages from Discord, Telegram, Slack, or WhatsApp and route them to agents.',
    features: ['Connect Discord, Telegram, Slack, or WhatsApp bots', 'Route incoming messages to any agent', 'Each platform channel gets its own chat thread', 'Start and stop connectors from the UI'],
  },
  inbox: {
    icon: 'inbox',
    title: 'Inbox',
    description: 'Inspect external connector conversations in a dedicated inbox, separated from the main agent chats.',
    features: ['Filter by connector platform', 'Switch between connector instances', 'Review isolated sender transcripts', 'Keep the main chat focused on your own thread'],
  },
  webhooks: {
    icon: 'webhook',
    title: 'Webhooks',
    description: 'Receive external events over HTTP and route them into agent-driven workflows automatically.',
    features: ['Create secure inbound webhook endpoints', 'Filter events by type or source', 'Route each webhook to a specific agent', 'Use x-webhook-secret for request authentication'],
  },
  mcp_servers: {
    icon: 'server',
    title: 'MCP Servers',
    description: 'Connect agents to external MCP (Model Context Protocol) servers, injecting their tools into agent chats.',
    features: ['Configure stdio, SSE, or streamable HTTP transports', 'Test connections and discover available tools', 'Assign MCP servers to specific agents', 'Tools appear alongside built-in tools in chat'],
  },
  knowledge: {
    icon: 'globe',
    title: 'Knowledge Base',
    description: 'A shared knowledge graph accessible by all agents for cross-workspace information sharing.',
    features: ['Create tagged knowledge entries', 'Agents can store and search knowledge via tools', 'Full-text and vector search', 'Provenance tracking per entry'],
  },
  logs: {
    icon: 'file-text',
    title: 'Logs',
    description: 'View application logs, errors, and debug information. Logs auto-refresh in real-time.',
    features: ['Filter by level: ERROR, WARN, INFO, DEBUG', 'Search through log entries', 'Auto-refresh with live mode', 'Click entries to expand details'],
  },
  plugins: {
    icon: 'puzzle',
    title: 'Plugins',
    description: 'Extend agent behavior with hooks. Install from the marketplace, a URL, or drop .js files into data/plugins/.',
    features: ['Install plugins from the marketplace or a URL', 'Toggle plugins on/off', 'Lifecycle hooks: beforeChat, afterChat, onError', 'Compatible with OpenClaw plugin format'],
  },
  usage: {
    icon: 'bar-chart',
    title: 'Usage',
    description: 'Track token usage and costs across all providers and agents.',
    features: ['Per-provider cost breakdown', 'Token usage over time', 'Per-agent cost tracking', 'Export usage data'],
  },
  runs: {
    icon: 'activity',
    title: 'Runs',
    description: 'View the run queue and execution history.',
    features: ['Monitor queued and running tasks', 'View run results and errors', 'Cancel pending runs', 'Automatic retry tracking'],
  },
  settings: {
    icon: 'settings',
    title: 'Settings',
    description: 'Manage app defaults, providers, encrypted secrets, and automation settings.',
    features: ['Choose your default agent shortcut', 'Configure LLM providers and credentials', 'Tune heartbeat and autonomy settings', 'Set up voice, embeddings, and search'],
  },
  projects: {
    icon: 'folder',
    title: 'Projects',
    description: 'Organize your work into projects. Group agents, tasks, and schedules under a common scope.',
    features: ['Create named projects with color badges', 'Assign agents and tasks to projects', 'Filter sidebar views by project', 'Global view when no filter is active'],
  },
  activity: {
    icon: 'clock',
    title: 'Activity',
    description: 'Audit trail of all entity mutations across the system.',
    features: ['Track agent, task, and connector changes', 'Filter by entity type and action', 'Real-time updates via WebSocket', 'Relative timestamps'],
  },
  wallets: {
    icon: 'wallet',
    title: 'Wallets',
    description: 'Agent crypto wallets for autonomous financial operations on Solana.',
    features: ['Create Solana wallets for agents', 'Per-transaction and daily spending limits', 'User approval for transactions', 'Balance tracking and transaction history'],
  },
}

export const FULL_WIDTH_VIEWS = new Set<AppView>([
  'home', 'inbox', 'chatrooms', 'schedules', 'secrets', 'providers', 'skills',
  'connectors', 'webhooks', 'mcp_servers', 'knowledge', 'plugins',
  'usage', 'wallets', 'runs', 'logs', 'settings', 'activity', 'projects',
])
